// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.25.0
// source: admins.sql

package queries

import (
	"context"
)

const getAllAdmins = `-- name: GetAllAdmins :many
select id, player_name, player_steamid, flags, immunity, server_id, ends, created, group_id from sa_admins
`

func (q *Queries) GetAllAdmins(ctx context.Context) ([]SaAdmin, error) {
	rows, err := q.db.QueryContext(ctx, getAllAdmins)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []SaAdmin
	for rows.Next() {
		var i SaAdmin
		if err := rows.Scan(
			&i.ID,
			&i.PlayerName,
			&i.PlayerSteamid,
			&i.Flags,
			&i.Immunity,
			&i.ServerID,
			&i.Ends,
			&i.Created,
			&i.GroupID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
