// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.25.0

package queries

import (
	"database/sql"
	"time"
)

type SaAdmin struct {
	ID            int32
	PlayerName    sql.NullString
	PlayerSteamid string
	Flags         sql.NullString
	Immunity      int32
	ServerID      sql.NullInt32
	Ends          sql.NullTime
	Created       time.Time
	GroupID       sql.NullInt32
}

type SaServer struct {
	ID       int32
	Hostname sql.NullString
	Address  string
}
